# Generated by Django 4.2.15 on 2024-09-23 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='created_by',
        ),
    ]
